# Generated by Django 5.0.1 on 2024-01-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, null=True)),
                ('price', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, null=True)),
                ('email', models.TextField(max_length=100, null=True)),
                ('mob', models.PositiveIntegerField(null=True)),
                ('password', models.TextField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'seller',
            },
        ),
    ]
